# Generated by Django 3.2.16 on 2023-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_num', models.CharField(max_length=50, verbose_name='Номер тикета')),
                ('user_login', models.CharField(max_length=50, verbose_name='Логин юзера')),
                ('user_text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('admin_text', models.TextField(blank=True, null=True, verbose_name='Ответ модератора')),
                ('admin_date', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
            options={
                'verbose_name': 'Диалоги по тикетам',
                'verbose_name_plural': 'Диалоги по тикетам',
            },
        ),
    ]
