# Generated by Django 3.2.16 on 2023-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='order_num',
            field=models.IntegerField(default=-1),
        ),
    ]
