# Generated by Django 3.2.16 on 2023-08-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogWithOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юзер пользователя')),
                ('user_text', models.TextField(verbose_name='Текст пользователя')),
                ('admin_name', models.CharField(choices=[('Модератор', 'Модератор'), ('Обменник', 'Обменник')], max_length=100, verbose_name='Кто отвечает юзеру')),
                ('admin_text', models.TextField(verbose_name='Ответ админа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('admin_date', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('order_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Диалог по поводу обмена',
                'verbose_name_plural': 'Диалоги по поводу обменна',
            },
        ),
        migrations.CreateModel(
            name='ExchangeOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название обменника')),
                ('method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метод')),
                ('user_login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин юзера')),
                ('rek', models.BooleanField(default=False, verbose_name='Статус')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Размер')),
                ('amount_in_BTC', models.FloatField(blank=True, null=True, verbose_name='Размер в BTC')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Тотал')),
                ('comission', models.IntegerField(blank=True, null=True, verbose_name='Комиссия')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('committed', models.BooleanField(default=False, verbose_name='Действия')),
            ],
            options={
                'verbose_name': 'Обмены пользователя',
                'verbose_name_plural': 'Обмены пользователя',
            },
        ),
        migrations.CreateModel(
            name='ExchangerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('directions', models.CharField(max_length=100, verbose_name='Направления')),
                ('deposit', models.FloatField(verbose_name='Депозит')),
                ('commission', models.FloatField(verbose_name='Комиссия')),
                ('method', models.CharField(max_length=250, verbose_name='Методы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rules', models.TextField(verbose_name='Правила')),
                ('isAvailable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Обменник',
                'verbose_name_plural': 'Обменники',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=150, verbose_name='ник')),
                ('date', models.CharField(max_length=150, verbose_name='дата')),
                ('text', models.TextField(verbose_name='текст')),
                ('buys', models.IntegerField(verbose_name='покупок')),
                ('is_from_admin', models.BooleanField(verbose_name='от админа?')),
                ('exchanger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchangers.exchangerlist', verbose_name='Обменник')),
            ],
        ),
    ]
