# Generated by Django 3.2.16 on 2023-08-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_s.city')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='goods_img/', verbose_name='Обложка')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('min_price', models.FloatField(verbose_name='Минимальная цена')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('category', models.CharField(blank=True, choices=[('apteka', 'Аптека'), ('dissociatives', 'Диссоциативы'), ('Marijuana', 'Марихуана'), ('Opiates', 'Опиаты'), ('Psychedelics', 'Психоделики'), ('Stimulants', 'Стимуляторы'), ('Chemical', 'Химические реактивы/Конструкторы'), ('Ecstasy', 'Экстази'), ('Entheogens', 'Энтеогены'), ('Euphoretics', 'Эйфоретики'), ('Mixtures', 'Основа курительных смесей'), ('Other', 'Другoе'), ('Work', 'Работа'), ('Medicine', 'Медицина'), ('Advert', 'Реклама'), ('Earn', 'Способы заработка'), ('Fake', 'Фальшивые деньги'), ('Cannabinoids', 'Каннабинойды'), ('Grove', 'Товары для грова')], max_length=200, null=True, verbose_name='Категория товаров')),
                ('is_popular', models.BooleanField(verbose_name='Отображать в популярных товарах?')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.stores', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='GoodLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Тайник', 'Тайник'), ('Магнит', 'Магнит'), ('Прикоп', 'Прикоп'), ('Предзаказ', 'Предзаказ'), ('Снежный прикоп', 'Снежный прикоп'), ('Без типа', 'Без типа'), ('Клад в подъезде', 'Клад в подъезде'), ('Земляной прикоп', 'Земляной прикоп'), ('Супер стелс', 'Супер стелс - тайник'), ('Камень', 'Камень')], max_length=50, null=True, verbose_name='Тип')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Кол-во')),
                ('good', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_s.goods')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_s.location')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.IntegerField(null=True)),
                ('raiting', models.IntegerField(null=True)),
                ('nick_name', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('data', models.CharField(max_length=255, null=True)),
                ('comment_text', models.TextField(null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_s.goods')),
            ],
        ),
    ]
