# Generated by Django 3.2.16 on 2023-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юзер пользователя')),
                ('user_text', models.TextField(verbose_name='Текст пользователя')),
                ('admin_name', models.CharField(choices=[('Модератор', 'Модератор'), ('Магазин', 'Магазин')], max_length=100, verbose_name='Кто отвечает юзеру')),
                ('admin_text', models.TextField(verbose_name='Ответ админа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('admin_date', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
            options={
                'verbose_name': 'Диалоги по поводу диспутов',
                'verbose_name_plural': 'Диалоги по поводу диспутов',
            },
        ),
    ]
