# Generated by Django 3.2.16 on 2023-08-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_disputedialog_dispute_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputedialog',
            name='order_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер'),
        ),
    ]
