# Generated by Django 3.2.16 on 2023-08-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_disputedialog_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputedialog',
            name='dispute_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
