# Generated by Django 3.2.16 on 2023-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_handlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.FloatField(blank=True, null=True, verbose_name='Курс')),
                ('rek', models.CharField(blank=True, max_length=250, null=True, verbose_name='Реквизиты')),
                ('forum_link1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на форум 1')),
                ('forum_link2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на форум 2')),
                ('forum_link3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на форум 3')),
                ('telegram_bot_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('lurkchat_bot_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lurkchat')),
                ('tor_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tor-ссылка')),
                ('canva', models.TextField(blank=True, null=True, verbose_name='Канва на начальном экране')),
            ],
            options={
                'verbose_name': 'Хэндлеры сайта',
                'verbose_name_plural': 'Хэндлеры сайта',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteHandlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.FloatField(blank=True, null=True, verbose_name='Курс')),
                ('rek', models.CharField(blank=True, max_length=250, null=True, verbose_name='Реквизиты')),
                ('forum_link1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на форум 1')),
                ('forum_link2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на форум 2')),
                ('forum_link3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на форум 3')),
                ('telegram_bot_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('lurkchat_bot_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lurkchat')),
                ('tor_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tor-ссылка')),
                ('canva', models.TextField(verbose_name='Канва на начальном экране')),
            ],
            options={
                'verbose_name': 'Хэндлеры сайта',
                'verbose_name_plural': 'Хэндлеры сайта',
            },
        ),
    ]
