# Generated by Django 3.2.16 on 2023-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='topstores_img/', verbose_name='Обложка')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('sold', models.IntegerField(blank=True, null=True, verbose_name='Продано')),
                ('deposit', models.FloatField(blank=True, null=True, verbose_name='Депозит')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('works', models.TextField(blank=True, null=True, verbose_name='Работа')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Правила магазина')),
                ('sales', models.TextField(blank=True, null=True, verbose_name='Акции')),
                ('forum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на форум')),
                ('store_type', models.CharField(blank=True, choices=[('Производитель', 'Производитель'), ('Оптовик', 'Оптовик'), ('Миниопт', 'Миниопт'), ('Непроверенный', 'Непроверенный')], max_length=80, null=True, verbose_name='Категория')),
                ('telegram_bot', models.URLField(blank=True, null=True, verbose_name='Телеграм-бот')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='topstores_img/', verbose_name='Шапка магазина')),
                ('is_crown', models.BooleanField(default=False, verbose_name='Корона')),
                ('is_top', models.BooleanField(default=False, verbose_name='Отображать в топ магазинах')),
                ('is_new', models.BooleanField(default=False, verbose_name='Отображать в топ оптовиках')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
